# Generated by Django 4.1.4 on 2022-12-29 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingUser',
            fields=[
                ('kd_mapuser', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.TextField(max_length=50)),
                ('kd_dept', models.CharField(max_length=20)),
                ('kd_bu', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"sc_mst"."mapping_user"',
            },
        ),
    ]
