# Generated by Django 4.1.4 on 2022-12-29 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('so', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLimbah',
            fields=[
                ('kode_grplbh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_grplbh', models.CharField(max_length=50)),
                ('desk_grplbh', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"sc_mst"."group_limbah"',
            },
        ),
        migrations.CreateModel(
            name='KategoriLimbah',
            fields=[
                ('kode_lbh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_lbh', models.CharField(max_length=50)),
                ('desk_lbh', models.TextField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"sc_mst"."kategori_limbah"',
            },
        ),
        migrations.CreateModel(
            name='SumberLimbah',
            fields=[
                ('kode_sbrlbh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desk_sbrlbh', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"sc_mst"."sumber_limbah"',
            },
        ),
        migrations.CreateModel(
            name='TujuanPenyimpananLimbah',
            fields=[
                ('kode_tplbh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desk_tplbh', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"sc_mst"."tujuan_limbah"',
            },
        ),
        migrations.CreateModel(
            name='SubGroupLimbah',
            fields=[
                ('kode_subgrplbh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_subgrplbh', models.CharField(max_length=50)),
                ('desk_subgrplbh', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('kode_grplbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.grouplimbah')),
            ],
            options={
                'db_table': '"sc_mst"."subgroup_limbah"',
            },
        ),
        migrations.CreateModel(
            name='LogbookLimbah',
            fields=[
                ('no_dokumen', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kode_bu', models.TextField(max_length=150)),
                ('kode_subdept', models.CharField(max_length=20)),
                ('tipe_trx', models.CharField(choices=[('IN', 'MASUK'), ('OUT', 'KELUAR')], max_length=4)),
                ('tgl_lbh', models.DateField()),
                ('tgl_max_lbh', models.DateField()),
                ('qty_lbh', models.FloatField()),
                ('evidence', models.TextField(max_length=250, null=True)),
                ('deksripsi', models.TextField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('I', 'MASUK'), ('P', 'TERKIRIM')], max_length=4)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('input_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('kode_grplbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.grouplimbah')),
                ('kode_lbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.kategorilimbah')),
                ('kode_sbrlbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.sumberlimbah')),
                ('kode_subbu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.subunitbisnis')),
                ('kode_subgrplbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.subgrouplimbah')),
                ('kode_tplbh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbah.tujuanpenyimpananlimbah')),
            ],
            options={
                'db_table': '"sc_trx"."logbook_limbah"',
            },
        ),
    ]
