# Generated by Django 4.1.4 on 2022-12-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BisnisUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bu', models.CharField(max_length=20)),
                ('nama_bu', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': '"sc_mst"."bisnis_unit"',
            },
        ),
        migrations.CreateModel(
            name='Departmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dept', models.CharField(max_length=20)),
                ('nama_dept', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('kode_bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.bisnisunit')),
            ],
            options={
                'db_table': '"sc_mst"."departmen"',
            },
        ),
        migrations.CreateModel(
            name='SubUnitBisnis',
            fields=[
                ('kode_subbu', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_subbu', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('kode_bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.bisnisunit')),
            ],
            options={
                'db_table': '"sc_mst"."subunit_bisnis"',
            },
        ),
        migrations.CreateModel(
            name='SubDepartmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_subdept', models.CharField(max_length=20)),
                ('nama_subdept', models.TextField(max_length=150)),
                ('inserted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('kode_bu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.bisnisunit')),
                ('kode_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.departmen')),
            ],
            options={
                'db_table': '"sc_mst"."sub_departmen"',
            },
        ),
    ]
